export const BankNameData = [
  { _id: 1, name: "National Bank of Pakistan" },
  { _id: 2, name: "Habib Bank Limited" },
  { _id: 3, name: "United Bank Limited" },
  { _id: 4, name: "MCB Bank Limited" },
  { _id: 5, name: "Allied Bank Limited" },
  { _id: 6, name: "Bank Alfalah Limited" },
  { _id: 7, name: "Askari Bank Limited" },
  { _id: 8, name: "Faysal Bank Limited" },
  { _id: 9, name: "Bank Al-Habib Limited" },
  { _id: 10, name: "Habib Metropolitan Bank" },
  { _id: 11, name: "Soneri Bank Limited" },
  {
    _id: 12,
    name: "Standard Chartered Bank",
  },
  { _id: 13, name: "Summit Bank Limited" },
  { _id: 14, name: "Silkbank Limited" },
  { _id: 15, name: "Sindh Bank Limited" },
  { _id: 16, name: "BankIslami Pakistan Limited" },
  { _id: 17, name: "Al Baraka Bank" },
  { _id: 18, name: "Dubai Islamic Bank" },
  { _id: 19, name: "JS Bank Limited" },
  { _id: 20, name: "Meezan Bank Limited" },
];
